version: '3'

services:

  simcomp:
    build: .
    ports:
      - '5000:5000'
    depends_on:
      - postgres
    container_name: orkg_similarity_comparison
    env_file: # Pass the environment variables in the .env file to the container
      - .env
    networks:
      - backend

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    container_name: es01
    environment:
    - node.name=es01
    - discovery.type=single-node # This is in dev mode
    #- discovery.seed_hosts=es02
    #- cluster.initial_master_nodes=es01,es02
    #- cluster.name=docker-cluster
    - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
    - esdata01:/usr/share/elasticsearch/data
    ports:
    - 9200:9200
    networks:
    - backend

  postgres:
    image: "postgres:11-alpine"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - 'postgres:/usr/share/postgresql/data'
    networks:
    - backend

volumes:
  esdata01:
    driver: local
  postgres:
    driver: local

networks:
  backend:
    external:
      name: orkgbackend_backend
