version: '3'

services:

  simcomp:
    build: .
    ports:
      - '5000:5000'
    container_name: orkg_similarity_comparison
    environment:
      - SIMCOMP_FLASK_HOST=0.0.0.0
      - SIMCOMP_FLASK_PORT=5000 # make sure that this port is exposed in ports
      #- SIMCOMP_FLASK_DEBUG=1
      - SIMCOMP_NEO4J_HOST=neo4j
      - SIMCOMP_ELASTIC_HOST=elastic:9200
    networks:
      - backend

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    container_name: es01
    environment:
    - node.name=es01
    - discovery.type=single-node # This is in dev mode
    #- discovery.seed_hosts=es02
    #- cluster.initial_master_nodes=es01,es02
    #- cluster.name=docker-cluster
    - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
    - esdata01:/usr/share/elasticsearch/data
    ports:
    - 9200:9200
    networks:
    - backend

  postgres:
    image: "postgres:11-alpine"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5555:5432"
    volumes:
      - 'postgres:/usr/share/postgresql/data'

volumes:
  esdata01:
    driver: local
  postgres:
    driver: local

networks:
  backend:
    external:
      name: orkg-backend_backend
