"""empty message

Revision ID: 4c7b4efa70de
Revises: 
Create Date: 2019-07-22 09:33:17.091645

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4c7b4efa70de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('long_url', sa.String(length=1000), nullable=True),
    sa.Column('short_code', sa.Unicode(length=64), nullable=True),
    sa.Column('contributions', sqlalchemy_utils.types.scalar_list.ScalarListType(), nullable=True),
    sa.Column('properties', sqlalchemy_utils.types.scalar_list.ScalarListType(), nullable=True),
    sa.Column('transpose', sa.Boolean(), nullable=True),
    sa.Column('json_code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_links_long_url'), ['long_url'], unique=False)
        batch_op.create_index(batch_op.f('ix_links_short_code'), ['short_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_links_short_code'))
        batch_op.drop_index(batch_op.f('ix_links_long_url'))

    op.drop_table('links')
    # ### end Alembic commands ###
